[package]
name = "picea"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1.7"
js-sys = "0.3.61"
wasm-bindgen = { version = "0.2.84" }

[dev-dependencies]
nannou = "0.18.1"
rand = "0.8.5"
